#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2012 Martin Ueding <dev@martin-ueding.de>

import argparse

def main():
    options = _parse_args()

    print options


def _parse_args():
    """
    Parses the command line arguments.

    @return: Namespace with arguments.
    @rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="%(prog)s action filenames", description="")
    parser.add_argument('action', metavar='action', type=str, nargs=1, help='Action.')
    parser.add_argument('filenames', metavar='filenames', type=str, nargs='+', help='Files to process.')
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument('--version', action='version', version='<the version>')

    return parser.parse_args()


if __name__ == "__main__":
    main()
