#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

import argparse
import os.path
import sys
from prettytable import PrettyTable

import picturedb

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()

    if not options.add is None:
        print "Tags to add:"
        print ', '.join(sorted(set(options.add)))
        print

    handle_input(options.filenames, options)


def handle_input(paths, options):
    files = []
    folders = []

    for path in paths:
        if os.path.isdir(path):
            folders.append(path)
        elif os.path.isfile(path):
            files.append(path)

    for folder in folders:
        handle_input(map(path_prepender(folder), os.listdir(folder)), options)

    if len(files) > 0:
        handle_files(files, options)


def path_prepender(path):
    """
    Generates a filter function that prepends the given path to each list item.

    :rtype: function
    """
    def filter(filename):
        """
        Prepends the set path to the filename.
        """
        return os.path.join(path, filename)

    return filter


def handle_files(files, options):
    table_data = []
    images = []
    for f in sorted(files):
        # Skip backup files.
        if f.endswith("~"):
            continue

        image = picturedb.Image(f)

        dirname = os.path.dirname(f)
        oldname = os.path.basename(f)
    
        if not options.add is None:
            for tag in options.add:
                image.add_tag(picturedb.Tag(tag))

        if not options.remove is None:
            for tag in options.remove:
                image.remove_tag(picturedb.Tag(tag))

        newname = os.path.basename(image.current_path())

        if image.name_changed() or (image.iptc_changed() and options.iptc):
            images.append(image)
            table_data.append([dirname, oldname, newname])

    if len(table_data) == 0:
        return

    print
    t = PrettyTable(["directory", "old name", "new name"])
    for row in table_data:
        t.add_row(row)
    print t
    print

    if options.y:
        answer = "y"
    else:
        answer = raw_input("Rename files? [Y/n] ")

    if answer != "n":
        for image in images:
            try:
                if options.iptc:
                    image.save()
                else:
                    image.rename()
            except OSError as e:
                print image, e


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(usage="%(prog)s [options --] filenames", description="")
    parser.add_argument('-a', "--add", metavar='tags', type=str, nargs='*', help='Tag to add.')
    parser.add_argument('-r', "--remove", metavar='tags', type=str, nargs='*', help='Tag to remove.')
    parser.add_argument('--iptc', action="store_true", help='Write IPTC tags.')
    parser.add_argument('-y', action="store_true", help="Don't ask questions")
    parser.add_argument('filenames', metavar='filenames', type=str, nargs='+', help='Files to process.')
    #parser.add_argument("", dest="", type="", default=, help=)
    #parser.add_argument('--version', action='version', version='<the version>')

    return parser.parse_args()


if __name__ == "__main__":
    main()
