#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

set -e
set -u

for tag
do
	cachedir="$HOME/.cache/picture-db-scripts/tags/$tag"

	rm -rf "$cachedir"
	mkdir -p "$cachedir"
	find "$HOME/Bilder/Bilder_Datenbank" -type f -name "*#$tag*" -print -exec ln -sr {} "$cachedir/" \;
done
